import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { ComparisonDashboard } from "@/components/compare/comparison-dashboard";

const api = vi.hoisted(() => ({ fetchSkus: vi.fn(), fetchWeeks: vi.fn(), fetchComparison: vi.fn(), fetchSkuDetail: vi.fn(), fetchSkuTrends: vi.fn(), fetchSkuEvidence: vi.fn() }));
const ask = vi.hoisted(() => ({ streamAsk: vi.fn() }));
vi.mock("@/lib/api/dashboard", () => api); vi.mock("@/lib/api/ask", () => ask);
const skus = [{ sku_code: "ecoflow-delta2", brand: "EcoFlow", model: "DELTA 2", capacity_wh: 1024, capacity_tier: "mid", is_competitor: false, dashboard_enabled: true }, { sku_code: "jackery-explorer-1000", brand: "Jackery", model: "Explorer 1000", capacity_wh: 1002, capacity_tier: "mid", is_competitor: true, dashboard_enabled: true }, { sku_code: "jackery-explorer-240", brand: "Jackery", model: "Explorer 240", capacity_wh: 240, capacity_tier: "entry", is_competitor: true, dashboard_enabled: true }, { sku_code: "jackery-explorer-300", brand: "Jackery", model: "Explorer 300", capacity_wh: 293, capacity_tier: "entry", is_competitor: true, dashboard_enabled: true }, { sku_code: "anker-solix-f2000", brand: "Anker", model: "SOLIX F2000", capacity_wh: 2048, capacity_tier: "large", is_competitor: true, dashboard_enabled: true }];
const weeks = [{ week_id: 202403, week_start: "2024-01-15", week_end: "2024-01-21", doc_count: 12, mention_count: 20, skus_covered: skus.map((sku) => sku.sku_code) }];
const citation = { mention_id: "00000000-0000-0000-0000-000000000101", document_id: "00000000-0000-0000-0000-000000000201", evidence_preview: "It lasted through the whole weekend.", sku_code: "ecoflow-delta2", aspect_label: "battery_capacity", sentiment: "positive" as const, week_id: 202403, source: { document_id: "00000000-0000-0000-0000-000000000201", sku_code: "ecoflow-delta2", platform: "amazon", published_at: null, source_url: null, title: null, rating: null, review_text: null } };
function renderPage() { const client = new QueryClient({ defaultOptions: { queries: { retry: false } } }); return render(<QueryClientProvider client={client}><ComparisonDashboard /></QueryClientProvider>); }
describe("ComparisonDashboard", () => { afterEach(() => cleanup()); beforeEach(() => { Object.values(api).forEach((mock) => mock.mockReset()); ask.streamAsk.mockReset(); api.fetchSkus.mockResolvedValue(skus); api.fetchWeeks.mockResolvedValue(weeks); api.fetchComparison.mockResolvedValue({ week_id: 202403, capacity_tier: "mid", skus: skus.slice(0, 2).map((sku) => ({ sku_code: sku.sku_code, review_count: 10, mention_count: 12, positive_count: 7, negative_count: 3, neutral_count: 2, positive_rate: 0.58, negative_rate: 0.25, neutral_rate: 0.17, sentiment_score: 0.33 })), warnings: [] }); api.fetchSkuDetail.mockImplementation((code: string) => Promise.resolve({ ...skus.find((sku) => sku.sku_code === code)!, week_id: 202403, review_count: 10, mention_count: 12, sentiment_breakdown: { positive: 7, negative: 3, neutral: 2 }, top_aspects: [{ aspect_label: "battery_capacity", mention_count: 8, positive_rate: 0.75 }] })); api.fetchSkuTrends.mockResolvedValue({ sku_code: "x", sku_name: "x", capacity_tier: "mid", trends: [] }); api.fetchSkuEvidence.mockResolvedValue([citation]); });
it("loads a same-tier pair and prevents cross-tier SKU B choices", async () => { renderPage(); await waitFor(() => expect(api.fetchComparison).toHaveBeenCalledWith("ecoflow-delta2", "jackery-explorer-1000", 202403)); await screen.findByText("Representative evidence"); const skuB = screen.getByLabelText("SKU B"); expect(within(skuB).queryByRole("option", { name: /SOLIX F2000/ })).not.toBeInTheDocument(); fireEvent.change(screen.getByLabelText("SKU A"), { target: { value: "jackery-explorer-240" } }); await waitFor(() => expect(within(screen.getByLabelText("SKU B")).getByRole("option", { name: /Explorer 300/ })).toBeInTheDocument()); expect(within(screen.getByLabelText("SKU B")).queryByRole("option", { name: /DELTA 2/ })).not.toBeInTheDocument(); });
it("renders grounded evidence and streams the existing Agent summary contract", async () => { ask.streamAsk.mockImplementation(async (_message: string, onEvent: (event: unknown) => void) => { onEvent({ event_type: "answer_delta", delta: "The data is grounded." }); onEvent({ event_type: "citation", citation }); onEvent({ event_type: "done", status: "success" }); }); renderPage(); await screen.findByText("Representative evidence"); expect(screen.getAllByText(/It lasted through the whole weekend/).length).toBeGreaterThan(0); fireEvent.click(screen.getByRole("button", { name: "Generate summary" })); await waitFor(() => expect(ask.streamAsk).toHaveBeenCalled()); expect(ask.streamAsk.mock.calls[0][0]).toContain("ecoflow-delta2"); expect(screen.getByText("The data is grounded.")).toBeInTheDocument(); }); });
