"use client";

import { useQuery } from "@tanstack/react-query";
import { GitCompareArrows, MessageSquareText } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { ControlledSummary } from "@/components/compare/controlled-summary";
import { EvidenceCard } from "@/components/evidence/evidence-card";
import { EmptyState, ErrorState, LoadingState } from "@/components/ui/states";
import { PageHeader, PageLayout, Surface } from "@/components/ui/page-layout";
import { fetchComparison, fetchSkuDetail, fetchSkuEvidence, fetchSkuTrends, fetchSkus, fetchWeeks, type ComparisonMetrics, type SkuDetailResponse, type SkuMetadata, type TrendPoint } from "@/lib/api/dashboard";
import { toApiError } from "@/lib/api/client";

function formatPercent(value: number) { return new Intl.NumberFormat("en-US", { style: "percent", maximumFractionDigits: 0 }).format(value); }
function formatNumber(value: number) { return new Intl.NumberFormat("en-US").format(value); }
function formatWeek(weekId: number) { return `${Math.floor(weekId / 100)} W${String(weekId % 100).padStart(2, "0")}`; }
function titleFromAspect(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (character) => character.toUpperCase()); }

function Selector({ label, value, options, onChange, disabled = false }: { label: string; value: string; options: SkuMetadata[]; onChange: (value: string) => void; disabled?: boolean }) {
  return <label className="block"><span className="block text-xs font-semibold uppercase tracking-[0.14em] text-[var(--ink-muted)]">{label}</span><select aria-label={label} value={value} disabled={disabled} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full rounded-lg border border-[var(--line)] bg-[var(--surface)] px-3 py-2 text-sm font-medium disabled:cursor-not-allowed disabled:opacity-60">{options.map((sku) => <option key={sku.sku_code} value={sku.sku_code}>{sku.brand} {sku.model} · {sku.capacity_tier ?? "unclassified"}</option>)}</select></label>;
}

function MetricComparison({ metrics, skus }: { metrics: ComparisonMetrics[]; skus: SkuMetadata[] }) {
  return <Surface className="mt-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[var(--ink-muted)]">Sentiment comparison</p><div className="mt-4 grid gap-4 md:grid-cols-2">{metrics.map((metric) => { const sku = skus.find((item) => item.sku_code === metric.sku_code); return <div key={metric.sku_code} className="rounded-lg bg-[var(--surface-muted)] p-4"><h2 className="font-semibold">{sku?.brand} {sku?.model}</h2><dl className="mt-4 grid grid-cols-3 gap-3 text-sm"><div><dt className="text-[var(--ink-muted)]">Positive</dt><dd className="mt-1 font-semibold">{formatPercent(metric.positive_rate)}</dd></div><div><dt className="text-[var(--ink-muted)]">Neutral</dt><dd className="mt-1 font-semibold">{formatPercent(metric.neutral_rate)}</dd></div><div><dt className="text-[var(--ink-muted)]">Negative</dt><dd className="mt-1 font-semibold">{formatPercent(metric.negative_rate)}</dd></div></dl><p className="mt-4 text-sm text-[var(--ink-muted)]">{formatNumber(metric.review_count)} reviews · {formatNumber(metric.mention_count)} mentions · score {metric.sentiment_score > 0 ? "+" : ""}{metric.sentiment_score.toFixed(2)}</p></div>; })}</div></Surface>;
}

function AspectPanel({ detail }: { detail: SkuDetailResponse }) { return <div><h3 className="font-semibold">{detail.brand} {detail.model}</h3><ul className="mt-3 space-y-2">{detail.top_aspects.map((aspect) => <li key={aspect.aspect_label} className="flex justify-between gap-3 text-sm"><span>{titleFromAspect(aspect.aspect_label)} <span className="text-[var(--ink-muted)]">({formatNumber(aspect.mention_count)})</span></span><span className="font-semibold">{formatPercent(aspect.positive_rate)} positive</span></li>)}</ul></div>; }
function TrendPanel({ sku, trends }: { sku: SkuMetadata; trends: TrendPoint[] }) { return <div><h3 className="font-semibold">{sku.brand} {sku.model}</h3>{trends.length ? <ul className="mt-3 space-y-2 text-sm">{trends.map((trend) => <li key={`${trend.week_id}-${trend.aspect_label}`} className="border-t border-[var(--line)] pt-2"><span className="font-medium">{formatWeek(trend.week_id)} · {titleFromAspect(trend.aspect_label)}</span><span className="block mt-1 text-[var(--ink-muted)]">+{trend.positive_count} · {trend.neutral_count} neutral · −{trend.negative_count}</span></li>)}</ul> : <p className="mt-3 text-sm text-[var(--ink-muted)]">No trend points available.</p>}</div>; }
function EvidencePanel({ sku, positive, negative }: { sku: SkuMetadata; positive: Awaited<ReturnType<typeof fetchSkuEvidence>>; negative: Awaited<ReturnType<typeof fetchSkuEvidence>> }) { const citations = Array.from(new Map([...positive.slice(0, 1), ...negative.slice(0, 1)].map((citation) => [citation.mention_id, citation])).values()); return <div><h3 className="font-semibold">{sku.brand} {sku.model}</h3>{citations.length ? <div className="mt-3 grid gap-3">{citations.map((citation) => <EvidenceCard key={citation.mention_id} citation={citation} />)}</div> : <p className="mt-3 text-sm text-[var(--ink-muted)]">No representative evidence for this week.</p>}</div>; }

export function ComparisonDashboard() {
  const [selectedA, setSelectedA] = useState(""); const [selectedB, setSelectedB] = useState(""); const [selectedWeek, setSelectedWeek] = useState<number | null>(null);
  const skusQuery = useQuery({ queryKey: ["skus"], queryFn: fetchSkus }); const weeksQuery = useQuery({ queryKey: ["weeks"], queryFn: fetchWeeks });
  const skuA = skusQuery.data?.find((sku) => sku.sku_code === selectedA) ?? skusQuery.data?.[0];
  const choicesB = skusQuery.data?.filter((sku) => sku.sku_code !== skuA?.sku_code && sku.capacity_tier === skuA?.capacity_tier) ?? [];
  const skuB = choicesB.find((sku) => sku.sku_code === selectedB) ?? choicesB[0];
  const commonWeeks = weeksQuery.data?.filter((week) => skuA && skuB && week.skus_covered.includes(skuA.sku_code) && week.skus_covered.includes(skuB.sku_code)) ?? [];
  const weekId = selectedWeek ?? commonWeeks[0]?.week_id;
  const enabled = Boolean(skuA && skuB && weekId !== undefined);
  const compareQuery = useQuery({ queryKey: ["compare", skuA?.sku_code, skuB?.sku_code, weekId], queryFn: () => fetchComparison(skuA!.sku_code, skuB!.sku_code, weekId as number), enabled });
  const detailA = useQuery({ queryKey: ["sku-detail", skuA?.sku_code, weekId], queryFn: () => fetchSkuDetail(skuA!.sku_code, weekId as number), enabled }); const detailB = useQuery({ queryKey: ["sku-detail", skuB?.sku_code, weekId], queryFn: () => fetchSkuDetail(skuB!.sku_code, weekId as number), enabled });
  const trendA = useQuery({ queryKey: ["sku-trends", skuA?.sku_code], queryFn: () => fetchSkuTrends(skuA!.sku_code), enabled: Boolean(skuA) }); const trendB = useQuery({ queryKey: ["sku-trends", skuB?.sku_code], queryFn: () => fetchSkuTrends(skuB!.sku_code), enabled: Boolean(skuB) });
  const posA = useQuery({ queryKey: ["sku-evidence", skuA?.sku_code, weekId, "positive"], queryFn: () => fetchSkuEvidence(skuA!.sku_code, weekId as number, "positive"), enabled }); const negA = useQuery({ queryKey: ["sku-evidence", skuA?.sku_code, weekId, "negative"], queryFn: () => fetchSkuEvidence(skuA!.sku_code, weekId as number, "negative"), enabled }); const posB = useQuery({ queryKey: ["sku-evidence", skuB?.sku_code, weekId, "positive"], queryFn: () => fetchSkuEvidence(skuB!.sku_code, weekId as number, "positive"), enabled }); const negB = useQuery({ queryKey: ["sku-evidence", skuB?.sku_code, weekId, "negative"], queryFn: () => fetchSkuEvidence(skuB!.sku_code, weekId as number, "negative"), enabled });
  const retry = () => [skusQuery, weeksQuery, compareQuery, detailA, detailB, trendA, trendB, posA, negA, posB, negB].forEach((query) => void query.refetch());
  if (skusQuery.isPending || weeksQuery.isPending) return <PageLayout><LoadingState title="Loading comparison choices" /></PageLayout>;
  if (skusQuery.isError || weeksQuery.isError) return <PageLayout><ErrorState title="Unable to load comparison choices" description={toApiError(skusQuery.error ?? weeksQuery.error).message} action={<button onClick={retry} className="rounded-lg bg-[var(--brand)] px-4 py-2 text-sm font-semibold text-white">Try again</button>} /></PageLayout>;
  if (!skuA || !skuB || !commonWeeks.length) return <PageLayout><PageHeader eyebrow="Controlled comparison" title="Compare SKUs" description="Only same-capacity-tier dashboard products can be compared." /><div className="mt-7">{skuA ? <Surface><div className="grid gap-4 md:grid-cols-2"><Selector label="SKU A" value={skuA.sku_code} options={skusQuery.data ?? []} onChange={(code) => { setSelectedA(code); setSelectedB(""); setSelectedWeek(null); }} /><Selector label="SKU B" value={skuB?.sku_code ?? ""} options={choicesB} disabled={!skuB} onChange={(code) => { setSelectedB(code); setSelectedWeek(null); }} /></div></Surface> : null}<div className="mt-5"><EmptyState title="No comparable pair is available" description="Choose a SKU with another dashboard-enabled product in the same capacity tier." /></div></div></PageLayout>;
  const error = compareQuery.error ?? detailA.error ?? detailB.error ?? trendA.error ?? trendB.error ?? posA.error ?? negA.error ?? posB.error ?? negB.error;
  if (error) return <PageLayout><ErrorState title="Unable to load comparison" description={toApiError(error).message} action={<button onClick={retry} className="rounded-lg bg-[var(--brand)] px-4 py-2 text-sm font-semibold text-white">Try again</button>} /></PageLayout>;
  if (compareQuery.isPending || detailA.isPending || detailB.isPending || trendA.isPending || trendB.isPending || posA.isPending || negA.isPending || posB.isPending || negB.isPending || !compareQuery.data || !detailA.data || !detailB.data) return <PageLayout><LoadingState title="Loading comparison signals" /></PageLayout>;
  const changeA = (code: string) => { setSelectedA(code); setSelectedB(""); setSelectedWeek(null); };
  return <PageLayout><PageHeader eyebrow="Controlled comparison" title="Compare SKUs" description="Neutral, server-validated comparison for a same-capacity-tier pair." /><div className="mt-7"><Surface><div className="grid gap-4 md:grid-cols-3"><Selector label="SKU A" value={skuA.sku_code} options={skusQuery.data ?? []} onChange={changeA} /><Selector label="SKU B" value={skuB.sku_code} options={choicesB} onChange={(code) => { setSelectedB(code); setSelectedWeek(null); }} /><label><span className="block text-xs font-semibold uppercase tracking-[0.14em] text-[var(--ink-muted)]">Covered week</span><select aria-label="Covered week" value={weekId} onChange={(event) => setSelectedWeek(Number(event.target.value))} className="mt-2 w-full rounded-lg border border-[var(--line)] bg-[var(--surface)] px-3 py-2 text-sm font-medium">{commonWeeks.map((week) => <option key={week.week_id} value={week.week_id}>{formatWeek(week.week_id)}</option>)}</select></label></div><p className="mt-4 flex items-center gap-2 text-sm text-[var(--ink-muted)]"><GitCompareArrows size={16} />SKU B is limited to the {skuA.capacity_tier ?? "selected"} tier; the backend enforces this rule independently.</p></Surface><MetricComparison metrics={compareQuery.data.skus} skus={[skuA, skuB]} /><ControlledSummary skuA={skuA.sku_code} skuB={skuB.sku_code} weekId={weekId} /><div className="mt-5 grid gap-5 xl:grid-cols-2"><Surface><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[var(--ink-muted)]">Aspect comparison</p><div className="mt-4 grid gap-5 md:grid-cols-2"><AspectPanel detail={detailA.data} /><AspectPanel detail={detailB.data} /></div></Surface><Surface><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[var(--ink-muted)]">Weekly trend comparison</p><div className="mt-4 grid gap-5 md:grid-cols-2"><TrendPanel sku={skuA} trends={trendA.data?.trends ?? []} /><TrendPanel sku={skuB} trends={trendB.data?.trends ?? []} /></div></Surface></div><Surface className="mt-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[var(--ink-muted)]">Representative evidence</p><div className="mt-4 grid gap-5 xl:grid-cols-2"><EvidencePanel sku={skuA} positive={posA.data ?? []} negative={negA.data ?? []} /><EvidencePanel sku={skuB} positive={posB.data ?? []} negative={negB.data ?? []} /></div></Surface><Link href="/ask" className="mt-5 inline-flex items-center gap-2 rounded-lg bg-[var(--brand)] px-4 py-2 text-sm font-semibold text-white"><MessageSquareText size={16} />Ask a follow-up</Link></div></PageLayout>;
}
